mesh: 
  periodic_bc: true 
  dim: 2 # 1 or 2 

  # 1D
  # L: 100.0
  # nCells: 100 # 1D 
  
  # 2D
  Lx: 100.0
  Ly: 100.0
  nCellsX: 100 # 2D
  nCellsY: 100 # 2D

model:
  a: 2.0        # Rainfall 
  alpha: 1.0    # Water intake rate
  v: 182.5      # Water velocity
  
  b1: 1.0       # Grass water absorption 
  m1: 0.45      # Grass mortality 
  d1: 1.0       # Grass diffusion 
  
  b2: 0.8       # Sapling absorption — slightly less than grass
  m2: 0.3       # Sapling mortality — lower than grass
  gamma: 0.2    # Sapling to tree conversion rate
  d2:  0.5       # Sapling diffusion (from tree diffusion term)
  phi: 0.05     # Sapling spread rate from trees
  
  b3: 0.2       # Tree absorption — less efficient than grass
  m3:  0.1       # Tree mortality — trees live longer
  
  type: extended # extended or klausmeier - just used for initial conditions, sets s0 = b0 = 0 if klausmeier
  # To match OG Klausmeier, use a = 2.0, alpha = 1.0, v = 182.5, b1 = 1.0, m1 = 0.45, d1 = 1.0, everything else to 0.0

terrain:
  enable: false

simulation: 
  totalTime: 100.0 
  dt: 0.002
  save_every: 100 
  seed: 42 
  eq_branch: E1+ # E0 (trivial), E1+ (grass only, positive branch), E1- (grass only, negative branch), E2_1/2/3/4 (saplings + trees), E_all (all coexist)
  perturbation: 0.001 # Size of random perturbation around equilibrium for initial conditions 

output:
  dir: outputs
  save_plot: true
  save_config: true
  save_animation: true  # gif - set to false for quick params sweeps
  

  
